# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'NbmapStoryboard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod ‘ios-maps-pod’, :git => “https://github.com/nextbillion-ai/ios-maps-pod.git”
  # pod 'nb-ios-maps',:git => 'https://github.com/nextbillion-ai/ios-maps-pod.git'

  target 'NbmapStoryboardTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NbmapStoryboardUITests' do
    # Pods for testing
  end

end
